### ISSUE TITLE
DEXSeq NA values in Log2Fold

### ISSUE THREAD

**Issue by Aufiero** [areyesq89/DEXSeq#10]
Hi,

I am writing since I run the DEXSeq workflow to find differentially expressed exons. In the results I noticed that there are some rows in which the coefficients and the corresponding log2Fold changes are set to NA, the counts of the samples seem reasonable (See attached table). What could be the reason for these NA values?

![dexseq](https://user-images.githubusercontent.com/12097373/110612259-4e11df80-8190-11eb-9fb9-edd01335cad1.png)

Thanks,
Best,
Simona

**Comment by chrarnold** [comment]
Hi, we face exactly the same issue, does someone know why? It looks like a bug to us.

**Comment by areyesq89** [comment]
Thanks for reporting this. This happens when the GLM fit that calculates the effect sizes in the estimateExonFoldChanges fails to converge. For these cases, which should be a minority, NA values are reported.  Closing this issue as it is out of our hands as DEXSeq developers.

**Comment by chrarnold** [comment]
It also happens, as in my case, when only exon from a gene is left because others have been filtered before running DEXSeq or because the gene has only one exon.

**Comment by Aufiero** [comment]
Why estimateExonFoldChanges fail to converge? What might be the reason?
How the pvalues and pAdj for those exons are then calculated if Log2FC is NA?

**Comment by parcbioinfo** [comment]
I have the same question as Aufiero: "How the pvalues and pAdj for those exons are then calculated if Log2FC is NA?" Could you clarify?
