### ISSUE TITLE
Setting Control Samples Using 'factor' And/Or 'relevel'

### ISSUE THREAD

**Issue by BenjaMcM** [areyesq89/DEXSeq#11]
I have experienced issues setting the correct group of samples as the control group. I understand that DEXSeq assigns a control condition based on the alphabetical order of the conditions (i.e. "Mutant" vs "WT", the "Mutant" samples would be set as the control group). I have attempted to correct for this by using 'factor' and/or 'relevel' to set the correct control group, which appears to work when I check the DEXSeq object structure. However when I visualize the results, the plots continue to show the incorrect comparison. Has anyone else experienced this issue? If so, how were you able to correct it?

**Comment by areyesq89** [comment]
Thanks for reporting this @BenjaMcM. Would you please clarify what do you mean with the plots showing the incorrect comparison?
