### ISSUE TITLE
DEXSeq NA values in Log2Fold (#10 reopened)

### ISSUE THREAD

**Issue by parcbioinfo** [areyesq89/DEXSeq#12]
I have the same question as Aufiero: "How the pvalues and pAdj for those exons are then calculated if Log2FC is NA?" Could you clarify?

_Originally posted by @pdarakjiank in https://github.com/areyesq89/DEXSeq/issues/10#issuecomment-1075737486_

**Comment by areyesq89** [comment]
Thanks for your question @pdarakjiank. Two separate fits are done to calculate p-values and to calculate effect sizes. For more details please check the publication and the vignettes. If any of those fits fail to converge, then NAs are reported.

**Comment by parcbioinfo** [comment]
Thanks; that's what I wanted to make sure I had understood.
