### ISSUE TITLE
No counts where there should be counts

### ISSUE THREAD

**Issue by mibsmibs** [areyesq89/DEXSeq#14]
I have a data set that has counts over our gene of interest using DESeq but no counts at all over the same region using DEXSeq. Do you know how this could be? Is there an internal filter in the DEXSeq call?

**Comment by areyesq89** [comment]
Very likely. If paired-end, DEXSeq htcount script required both fragments to be mapped correctly and to be uniquely mapping. Either of these steps might be discarding read from being counted.
