### ISSUE TITLE
DEXseq Count files do not correspond to the flattened annotation file

### ISSUE THREAD

**Issue by liqianqian-123** [areyesq89/DEXSeq#16]
I created the count files using dexseq_count.py according to the instructions. However, when I used DEXSeqDataSetFromHTSeq, I get the following error:
Error in DEXSeqDataSetFromHTSeq(countFiles, sampleData = sampleTable,  : 
  Count files do not correspond to the flattened annotation file
Here is my code：

setwd("E:/1_科研/1_lncRNA/7_DTU&DEU/differential_exon_usage/HTSeq")
library("DEXSeq")
library("pasilla")

countFiles = list.files("E:/1_科研/1_lncRNA/7_DTU&DEU/differential_exon_usage/HTSeq", pattern=".txt$", full.names=TRUE)
flattenedFile = list.files("E:/1_科研/1_lncRNA/7_DTU&DEU/differential_exon_usage/HTSeq", pattern="gff$", full.names=TRUE)
sampleTable = data.frame(row.names = c( "Hai-05","Him-12","Him-13","Hai-16","Hai-19","Hai-20","Him-35","Him-36"),condition= c("hainanus", "himalayanus", "himalayanus", "hainanus", "hainanus", "hainanus", "himalayanus","himalayanus" ))

dxd = DEXSeqDataSetFromHTSeq(
  countFiles,
  sampleData=sampleTable,
  design= ~ sample + exon + condition:exon,
  flattenedfile=flattenedFile)

The following is my script for generating GTF files and txt files：
python /home/students/tools/DEXSeq/inst/python_scripts/dexseq_prepare_annotation.py /home/students/0_database/1_affinis_genemo_hisat2/affinis.genomic.gtf affinis.gff

python /home/students/tools/DEXSeq/inst/python_scripts/dexseq_count.py /home/students/3_qqli/7_lncRNA/nanopore_process/diffe_exon_usage/count/affinis.gff -p yes -f bam  /home/students/3_qqli/1_affinis_him_hainan_mRNA/hisat2_featurecounts/min_length_50_hisat2/190505.bam 05.txt

Txt files and GTF files are listed below：
###txt
Parent=evm.model.Contig1.100:001	997
Parent=evm.model.Contig1.100:002	1001
Parent=evm.model.Contig1.100:003	1074
Parent=evm.model.Contig1.100:004	625
Parent=evm.model.Contig1.100:005	1199
Parent=evm.model.Contig1.100:006	1111
Parent=evm.model.Contig1.100:007	1124
Parent=evm.model.Contig1.100:008	952
Parent=evm.model.Contig1.100:009	1413
Parent=evm.model.Contig1.101:001	0
Parent=evm.model.Contig1.101:002	0
Parent=evm.model.Contig1.101:003	0
Parent=evm.model.Contig1.102:001	14
Parent=evm.model.Contig1.102:002	17
Parent=evm.model.Contig1.102:003	16

###gtf
Contig1	dexseq_prepare_annotation.py	aggregate_gene	82977	99686	.	+	.	gene_id "Parent=evm.model.Contig1.1"
Contig1	dexseq_prepare_annotation.py	exonic_part	82977	82982	.	+	.	gene_id "Parent=evm.model.Contig1.1"; transcripts "Parent=evm.model.Contig1.1"; exonic_part_number "001"
Contig1	dexseq_prepare_annotation.py	exonic_part	84818	84934	.	+	.	gene_id "Parent=evm.model.Contig1.1"; transcripts "Parent=evm.model.Contig1.1"; exonic_part_number "002"
Contig1	dexseq_prepare_annotation.py	exonic_part	85276	85374	.	+	.	gene_id "Parent=evm.model.Contig1.1"; transcripts "Parent=evm.model.Contig1.1"; exonic_part_number "003"
Contig1	dexseq_prepare_annotation.py	exonic_part	85954	86096	.	+	.	gene_id "Parent=evm.model.Contig1.1"; transcripts "Parent=evm.model.Contig1.1"; exonic_part_number "004"
Contig1	dexseq_prepare_annotation.py	exonic_part	86527	86665	.	+	.	gene_id "Parent=evm.model.Contig1.1"; transcripts "Parent=evm.model.Contig1.1"; exonic_part_number "005"
Contig1	dexseq_prepare_annotation.py	exonic_part	90369	90512	.	+	.	gene_id "Parent=evm.model.Contig1.1"; transcripts "Parent=evm.model.Contig1.1"; exonic_part_number "006"
Contig1	dexseq_prepare_annotation.py	exonic_part	91229	91965	.	+	.	gene_id "Parent=evm.model.Contig1.1"; transcripts "Parent=evm.model.Contig1.1"; exonic_part_number "007"

I map the RNA-seq to the genome by hisat2 and produced bam files. The number of "exonic_part_number" in GTF and txt files were consistent, I feel that there is no problem with the files. I wonder if you can help me determine where the problem is, thank you very much!

**Comment by areyesq89** [comment]
Thanks for the detail post. I think it might be the non alphanumeric characters in the gene names that is causing the issue. Could you try to build the DEXSeqDataSet object manually?

**Comment by liqianqian-123** [comment]
Thank you for your reply. I modified the ID of the gene, and it can be run again.
