### ISSUE TITLE
disjointExons (GenomicFeatures) deprecation / removal

### ISSUE THREAD

**Issue by khoegenauer** [areyesq89/DEXSeq#2]
Looks like GenomicFeatures has deprecated `disjointExons` and will be removing it soon. It's replacement, `exonicParts`, returns the column "exon_rank" instead of "exonic_part"; "exon_rank" appears to be a transcript-wise exon ranking, instead of gene-wise, and contains multiple values where transcripts share an exon.

**Comment by areyesq89** [comment]
Thanks for pointing this out. Just added a fix to the development branch.
