### ISSUE TITLE
Vignette appearance

### ISSUE THREAD

**Issue by llrs** [areyesq89/DEXSeq#4]
Hi,

The current version of the vignette (and the devel version) shows the abstract of the vignette without bolds or italics letters. You might be able to fix it before the next release.

" \(\frac{\text{number of transcripts from the gene that contain this exon}} {\text{number of all transcripts from the gene}}\). 

"

**Comment by areyesq89** [comment]
Hi, 

The abstract looks fine to me both in the built vignettes in the Bioconductor website and the ones built in my computer. It might be that your browser is not rendering the equations properly for htmls. Are you able to see the rest of the equations from the vignette?

![image](https://user-images.githubusercontent.com/12632413/67410399-0e8e2780-f58a-11e9-9501-0e34967e30fd.png)

**Comment by llrs** [comment]
I checked with another browser and I could see the equations in the right format. I can't see other equations of the vignette. It must be something of my browser (Firefox) which I haven't found previously. Thanks, for the hint. 

BTW there is also the title "##Executability of the code" that needs a space "## Executability of the code"
