### ISSUE TITLE
DEXSeq python scripts output

### ISSUE THREAD

**Issue by OlgaVT** [areyesq89/DEXSeq#5]
Hi,

I used a dexseq_prepare_annotation.py and dexseq_count.py scripts on the human gtf annotation and RNA-Seq alignments. Some lines look like:
ENSG00000288258+ENSG00000182712+ENSG00000214827:001

Maybe I overlooked in the manual, what these "+" mean. Could you help me? Thank you!

**Comment by areyesq89** [comment]
Hi @OlgaVT. Please have a look at the script's help, there is a parameter that specifies the behaviour when two genes share one exon. One option is to merge these gene identifiers with a "+" separator, another option is to leave the genes unmerged and ignore the common exon.
